stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_PROJECT_NAME: visa_ds_160_state

image:
  name: docker:28.1.1
services:
  - docker:28.1.1-dind

# before_script:
#   - apk add --no-cache docker-compose

build:
  stage: build
  script:
    - docker compose -f docker-compose.prod.yml build
  # only:
  #   - main

test:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    # - docker compose up -d
    # - docker compose exec app npm test
    # - docker compose down
  # only:
  #   - merge_requests
  #   - main

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Add deployment steps here
    - docker compose -f docker-compose.prod.yml up -d
  # only:
  #   - tags

# For nextjs build caching https://nextjs.org/docs/app/guides/ci-build-caching
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - frontend/node_modules/
    - frontend/.next/cache/
